version: '2'
services:
  mongodb:
    image: mongo
    ports:
     - "27017:27017"
    volumes:
     - /Users/Max/dev/mongo_data/dump:/data
  mysqldb:
    image: mysql
    volumes:
      - /Users/Max/dev/mysql_data:/var/lib/mysql
     ports:
      - "3306:3306"
      environment:
      - MYSQL_ROOT_PASSWORD=alexandra


